baseURL: https://stephentuso.com/
languageCode: en-us
title: Stephen Tuso
theme: PaperMod
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

disqusShortname: stephentuso
googleAnalytics: G-WE40RSXBYG

params:
  comments: true
  ShowCodeCopyButtons: true
  homeInfoParams:
    Title: Hello there
    Content:
      These posts will mostly be notes and instructions for things that I want
      to reference later, but maybe they'll be useful to someone else out there
      too.

  socialIcons:
    - name: "github"
      url: "https://github.com/stephentuso"
